# Run this job on pushes to `main`, and for pull requests. If you don't specify
# `branches: [main], then this actions runs _twice_ on pull requests, which is
# annoying.

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTEST_RUN_PATH: tests

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Install annotation plugins
        run: uv pip install pytest-github-actions-annotate-failures

      - name: Run tests
        run: uv run pytest
